### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Teicu** [swisskyrepo/Subdomino#1]
Hi, can you tell me please how to fix this error. Thank you 

[OPTION] Google Scan enabled
[+] Crawl from Google...
Traceback (most recent call last):
  File "Subdomino.py", line 58, in <module>
    crawl_website_for_subdomain(opt_dork[0],int(opt_dork[1]), results.domain, int(results.threads), opt_dork[2], opt_dork[3])
  File "/root/Subdomino/subdomain_enum.py", line 108, in crawl_website_for_subdomain
    pool_outputs = pool.map(crawl_website_for_subdomain_extract, stuff_that_needs_getting) #function, arg(=list of hosts)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
requests.exceptions.ConnectionError: None: Max retries exceeded with url: /search?q=site:*.site.com%20-www.site.com&start=80 (Caused by None)

**Comment by swisskyrepo** [comment]
" Max retries exceeded with url: /search?q=site:*.site.com%20-www.site.com&start=80"
Perhaps you are banned by Google, retry later with a fewer thread ^^
Can you provide the command line you used ?

**Comment by Teicu** [comment]
Sure, I used "sudo python Subdomino.py --domain twitter.com --nmap --all --google 5 --yahoo 5 --bing 5 --baidu 5 --reversedns --names big_names.txt --threads 20"
  
btw, works fine if I do sudo python Subdomino.py --domain twitter.com

Regards

**Comment by swisskyrepo** [comment]
If you provide "--all" it will select "google, yahoo, reversedns and all other scanning methods" for you.
But the "reversedns" require the script to be run with "sudo" because it will check if the host is up by pinging it.

That's why you needed "sudo ..." :)
